
logging:
  file: "logs/sso-config.log"
info:
  name: "配置中心"
---
server:
  port: 8888
  servlet:
    context-path: /config
spring:
  profiles:
    active:
      - native
  application:
    name: sso-config
